name: Sandbox Workflow
run-name: Workflow on ${{ github.ref }} by @${{ github.actor }}

on: push

jobs:
  setting-summaries:
    name: 'Setting summaries'
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Generate list using Markdown
        run: |
          echo "# Step Summary" >> $GITHUB_STEP_SUMMARY
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
  summary-script:
    name: 'Setting summaries from within a script'
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        id: random-color-generator
        run: node .github/workflows/summary-generator.js
