name: Update showtimes
run-name: Update showtimes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 2'

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  BASE_URL: ${{ secrets.BASE_URL }}
  PARTNER_KEY: ${{ secrets.PARTNER_KEY }}
  TMDB_KEY: ${{ secrets.TMDB_KEY }}

jobs:
  automated-tasks:
    name: Automated tasks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
      - id: install
        name: Install dependencies
        run: yarn
      - id: mk2
        name: Get latest showtimes for MK2
        run: yarn run seed showtimes mk2
      - name: Get latest TMDB data
        run: yarn run seed movies tmdb
  setting-summaries:
    name: 'Setting summaries'
    runs-on: ubuntu-latest
    needs: [automated-tasks]
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Generate list using Markdown
        run: |
          echo "# Ciaocine Automation" >> $GITHUB_STEP_SUMMARY
          echo "Another successful run of the Ciaocine automation!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- [x] Added showtimes" >> $GITHUB_STEP_SUMMARY
          echo "- [x] Added MK2 showtimes" >> $GITHUB_STEP_SUMMARY
          echo "- [x] Added tmdb information" >> $GITHUB_STEP_SUMMARY
  summary-script:
    name: 'Setting summaries from within a script'
    runs-on: ubuntu-latest
    needs: [automated-tasks]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        id: random-color-generator
        run: node .github/workflows/summary-generator.js
