name: Schedule
run-name: Scheduled build

on:
  workflow_call:
  schedule:
    - '0 7 * * 1,2'

jobs:
  automated-tasks:
    name: Automated tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-{{ hash(package-lock.json) }}
      - name: Install dependencies
        run: npm install
      - name: Get latest showtimes
        run: npm run seed showtimes create
      - name: Get latest showtimes for MK2
        run: npm run seed showtimes mk2
      - name: Get latest TMDB data
        run: npm run seed movies tmdb
  setting-summaries:
    name: 'Setting summaries'
    runs-on: ubuntu-latest
    needs: [automated-tasks]
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Generate list using Markdown
        run: |
          echo "# Ciaocine Automation" >> $GITHUB_STEP_SUMMARY
          echo "Another successful run of the Ciaocine automation!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- [x] Added showtimes" >> $GITHUB_STEP_SUMMARY
          echo "- [x] Added MK2 showtimes" >> $GITHUB_STEP_SUMMARY
          echo "- [x] Added tmdb information" >> $GITHUB_STEP_SUMMARY
  summary-script:
    name: 'Setting summaries from within a script'
    runs-on: ubuntu-latest
    needs: [automated-tasks]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run script
        id: random-color-generator
        run: node .github/workflows/summary-generator.js
